### ISSUE TITLE
.tmux.conf being ignored

### ISSUE THREAD

**Issue by mircsicz** [gpakosz/.tmux#582]
Hi hi,

so far I've been using your awesome config for several month on my mac. But I can't use it on fedora, it seems to be ignored and if I try to manually load it from within a tmux (tmux source-file ~/.tmux.conf) window I get the following feedback:

`'cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned 2`

hope yoou got a hint...

**Comment by gpakosz** [comment]
Hello @mircsicz 👋

Can you please launch tmux and then from a page run
```
$ cut -c3- ~/.tmux.conf | sh -sx _apply_configuration
```
And paste the output here?

**Comment by mircsicz** [comment]
@gpakosz thx for taking the time

`
mircsicz@M720q:~$ cut -c3- ~/.tmux.conf | sh -sx _apply_configuration
+ :
+ set -e
+ unset GREP_OPTIONS
+ export LC_NUMERIC=C
+ LC_NUMERIC=C
+ sed -E s///
+ printf ''
++ uname -s
+ _uname_s=Linux
++ tmux -V
++ awk '{gsub(/[^0-9.]/, "", $2); print ($2+0) * 100}'
+ _tmux_version=320
+ command -v pkill
sh: Zeile 750: !\s+: event not found
sh: Zeile 756: !\bssh\b: event not found
sh: Zeile 761: Syntaxfehler beim unerwarteten Symbol »(«
`

**Comment by gpakosz** [comment]
So far I have no idea. 

- Can you please make sure you're running the most recent commit of `.tmux.conf?
- Can you please make sure you didn't modify `.tmux.conf`?
- Can you please tell me which version of Fedora you're running, and which shell?

**Comment by mircsicz** [comment]
> So far I have no idea.
> 
> * Can you please make sure you're running the most recent commit of `.tmux.conf?

```
mircsicz@M720q:~/.tmux$ git pull
remote: Enumerating objects: 21, done.
remote: Counting objects: 100% (17/17), done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 21 (delta 12), reused 10 (delta 10), pack-reused 4
Entpacke Objekte: 100% (21/21), 22.04 KiB | 1.47 MiB/s, fertig.
Von https://github.com/gpakosz/.tmux
   9a2387c..18a111f  master     -> origin/master
Aktualisiere 9a2387c..18a111f
Fast-forward
 .tmux.conf       | 121 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-----------------------------------------
 .tmux.conf.local |  25 +++++++++++++++++++------
 2 files changed, 99 insertions(+), 47 deletions(-)
mircsicz@M720q:~/.tmux$ cd -
/home/mircsicz
mircsicz@M720q:~$ cut -c3- ~/.tmux.conf | sh -sx _apply_configuration
+ :
+ set -e
+ unset GREP_OPTIONS
+ export LC_NUMERIC=C
+ LC_NUMERIC=C
+ sed -E s///
+ printf ''
++ uname -s
+ _uname_s=Linux
++ tmux -V
++ awk '{gsub(/[^0-9.]/, "", $2); print ($2+0) * 100}'
+ _tmux_version=320
+ command -v pkill
sh: Zeile 774: !\s+: event not found
sh: Zeile 781: !\bssh\b: event not found
sh: Zeile 785: Syntaxfehler beim unerwarteten Symbol »(«
```

> * Can you please make sure you didn't modify `.tmux.conf`?

see my "git pull"

> * Can you please tell me which version of Fedora you're running, and which shell?

```
mircsicz@M720q ~ $  cat /etc/redhat-release
Fedora release 36 (Thirty Six)
mircsicz@M720q ~ $  bash --version
GNU bash, Version 5.1.16(1)-release (x86_64-redhat-linux-gnu)
```

**Comment by gpakosz** [comment]
Which version of `perl` do you have?

**Comment by mircsicz** [comment]
mircsicz@M720q ~ $  perl -v

This is perl 5, version 34, subversion 1 (v5.34.1) built for x86_64-linux-thread-multi

**Comment by gpakosz** [comment]
I can't reproduce your issue so far

```
$ vagrant init generic/fedora36
$ vagrant up
$ vagrant ssh
$ cd
$ sudo dnf -y install tmux
$ git clone https://github.com/gpakosz/.tmux.git
$ ln -s .tmux/.tmux.conf
$ tmux
```
<img width="841" alt="image" src="https://user-images.githubusercontent.com/553208/182047685-ff9ecef4-01e4-4c90-8de9-96ea49df6f11.png">

**Comment by mircsicz** [comment]
I've two physical machines and one vm all quite fresh setup, all with same config'S deployed by ansible where it hits:

[Screenshot](https://snipboard.io/O1789o.jpg)

**Comment by gpakosz** [comment]
Can you share that ansible conf?

**Comment by mircsicz** [comment]
Sure, just installing vagrant to reproduce your test... Gi'me a sec

**Comment by mircsicz** [comment]
There u go:

```
---
- name: Copy dotfiles and/or configs to the host(s)
  hosts: "{{machines}}"
  gather_facts: false
  become: true
  vars:
    tmpldir: ~/ansible/templates/mircsicz/

  tasks:
    - set_fact:
      remote_user: "{{remoteuser}}"
    - name: Add nopasswd entry for {{remoteuser}} to sudoers.d
      ansible.builtin.template:
        src: '{{ tmpldir }}/sudoers.d-mircsicz.j2'
        dest: '/etc/sudoers.d/{{remoteuser}}'
        validate: /usr/sbin/visudo -cf %s
      tags:
        - sudo

    - name: Copy dotfiles
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dst }}"
        owner: "{{ remoteuser }}"
        group: "{{ remoteuser }}"
      with_items:
        - { src: '{{ tmpldir }}.tmux', dst: '/home/{{ remoteuser }}/' }
        - { src: '{{ tmpldir }}.tmuxinator', dst: '/home/{{ remoteuser }}/' }
        - { src: '{{ tmpldir }}.vimrc', dst: '/home/{{ remoteuser }}/' }
       - { src: '{{ tmpldir }}.bash_aliases', dst: '/home/{{ remoteuser }}/' }
        - { src: '{{ tmpldir }}.bash_profile', dst: '/home/{{ remoteuser }}/' }
        - { src: '{{ tmpldir }}.profile', dst: '/home/{{ remoteuser }}/' }
        - { src: '{{ tmpldir }}.config', dst: '/home/{{ remoteuser }}/' }
      tags:
        - files
    - name: Create symlinks
      ansible.builtin.file:
        src: "{{ item.src }}"
        dest: "{{ item.dst }}"
        state: link
      with_items:
        - { src: '/home/{{ remoteuser }}/.tmux/.tmux.conf', dst: '/home/{{ remoteuser }}/.tmux.conf' }
        - { src: '/home/{{ remoteuser }}/.tmux/.tmux.conf.local', dst: '/home/{{ remoteuser }}/.tmux.conf.local' }
      tags:
        - files

- name: Install basic Apps
  ansible.builtin.import_playbook: play_user-apps.yml
  tags:
    - apps
```

which is run like this:
`ansible-playbook -i hosts_my_inv.yml myplay.yml --extra-vars "machines=myhostgroup remoteuser=mircsicz --ask-become-pass --tags=files,apps -vv
`
