### ISSUE TITLE
“run '~/.tmux/plugins/tpm/tpm'” has no effect in .tmux.conf.local

### ISSUE THREAD

**Issue by tripleCC** [gpakosz/.tmux#61]
```
# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
#
# # Other examples:
# # set -g @plugin 'github_username/plugin_name'
# # set -g @plugin 'git@github.com/user/plugin'
# # set -g @plugin 'git@bitbucket.com/user/plugin'
#
# # Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
```
This was the code I added to .tmux.conf.local at the bottom. But it seems that tpm could't run as I expected.

When I added the code to .tmux.conf and  reloaded the configuration，the error below was throwed：

```
'cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned 127
```

But the strange thing was that I could use plugin of tmux normally this time. Spliting new pane would also throw the error.

How could I fix the error ? Any suggestion would be appreciated.

**Comment by gpakosz** [comment]
Hello @tripleCC, I'm not a TPM user myself.

```
'cut -c3- ~/.tmux.conf | sh -s _apply_configuration' returned 127
```

This error usually means the `tmux` executable is not found in the path. You may want to see the output of
```
$ tmux run 'echo $PATH'
```

However, as far as I can tell, there's no straightforward way to make my configuration compatible with TPM:
  - I'm not familiar with TPM implementation
  - This would likely require changes on both sides
  - Using both kind-of defeats the purpose of having an easily transportable tmux configuration anyways

**Comment by vpassapera** [comment]
TPM works fine for me. But you have to add it to .tmux.conf instead of the .local one.

**Comment by vpassapera** [comment]
So, this is what I have in my ansible config and it seems to work.

```
    - name: Append to tmux configuration [.conf] (Plugins, etc)
      lineinfile:
        path: "/home/vpassapera/.tmux.conf"
        insertbefore: '# EOF'
        line: "{{ item }}"
      with_items:
        - set -g @plugin 'tmux-plugins/tpm'
        - set -g @plugin 'tmux-plugins/tmux-yank'
        - run '~/.tmux/plugins/tpm/tpm'
```

Have to do it on the .conf one. Before the line "#EOF" (This part is important).
